In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [10]:
a = np.array([[1,2,3],[4,5,6]], dtype = complex)
print(a)

[[1.+0.j 2.+0.j 3.+0.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [11]:
a = np.array([[1,2,3],[4,5,6]], dtype = float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [17]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [19]:
dt = np.dtype(np.int32)
print(dt)

int32


In [20]:
# int8, int16, int32,int64 四种数据类型可以使用字符串‘i1,i2,i4,i8'代替
dt = np.dtype('i4')
print(dt)

int32


In [22]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)
a = np.array([('abc',21,50),('xyz',18,75)], dtype = student)
print(a)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]
[(b'abc', 21, 50.) (b'xyz', 18, 75.)]


In [24]:
a = np.arange(24)
print(a.ndim) # a 现在只有一个维度
# 现在调整其大小
b = a.reshape(2,4,3)
print(b.ndim)

1
3


In [26]:
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [27]:
print(b.shape)

(2, 4, 3)


In [30]:
# 调整数组 大小
a.shape = (3,8) #总数据数量不能小于原数量，否则出错
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]


In [32]:
c = a.reshape(6,4)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [33]:
print(c.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [42]:
#1、 numpy.empty 方法用来创建一个指定形状（shape）、数据类型（dtype）且未初始化的数组：
# numpy.empty(shape, dtype = float, order = 'C') 
x = np.empty([3,2],dtype ='i8')
print(x)

[[4607182418800017408 4611686018427387904]
 [4613937818241073152 4616189618054758400]
 [4617315517961601024 4618441417868443648]]


In [50]:
#2、numpy.zeros 创建指定大小的数组，数组元素以0来填充
# numpy.empty(shape, dtype = float, order = 'C')
print("**************** X *****************")
x = np.zeros(5) #默认为浮点数
print(x)
# 设置类型为整数
print("**************** Y *****************")
y = np.zeros((5,), dtype= np.int)
print(y)
# 自定义类型
print("***************** Z ****************")
z = np.zeros((2,2), dtype = [('x','i4'),('y', 'i8')])
print(z)

**************** X *****************
[0. 0. 0. 0. 0.]
**************** Y *****************
[0 0 0 0 0]
***************** Z ****************
[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


In [52]:
#3、numpy.ones 创建指定形状的数组 ，数组元素以1来填充
# 默认为浮点娄
x = np.ones(5)
print(x)
print("*********************************")
# 自定义类型
x = np.ones([2,], dtype = 'i4')
print(x)

[1. 1. 1. 1. 1.]
*********************************
[1 1]


In [57]:
# 从已有的数组 创建数组
# numpy.asarray
# numpy.asarray(a,dtype = None, order = None)
# a  任意形式的输入参数，可以是，列表、列表的元组，元组，元组的元组，元组的列表，多给数组
# dtype 数据类型，可选
# order 可选，“C”：行优先“F”：列优先  ，在计算机内存中的存储元素的顺序。
import numpy as np

x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [58]:
# 将元组转换为 ndarray:
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [59]:
# 将元组列表转换为ndarray

x = [(1,2,3),(4,5)]
a = np.asarray(x)
print(a)

[(1, 2, 3) (4, 5)]


In [60]:
#设置了dtype参数：
x = [1,2,3]
a = np.asarray(x,dtype = float)
print(a)

[1. 2. 3.]


In [63]:
#4、numpy.frombuffer 用于实现动态数组，接受buffer输入参数，以流的形式转化成ndarray对象
# numpy.frombuffer(buffer,dtype= float, count = -1,offset = 0)
# buffer是字符串的时候，Python3默认str是Unicode类型，所以要转成bytestring在原str前加上b
# buffer 可以是任意对象，会以流的形式读入 dtype 返回数组 的数据类型，可选
# count 读取的数据数量，默认为-1，读取所有数据
# offset 读取的起始位置，默认为0

s = b"Hello world"
a = np.frombuffer(s, dtype = "S1")
print(a)

[b'H' b'e' b'l' b'l' b'o' b' ' b'w' b'o' b'r' b'l' b'd']


In [64]:
#5 、numpy.fromiter 从可迭代对象中建立ndarray对象，返回一维数组 。
# numpy.fromiter(iterable, dtype, count = -1)   count 读取数据数量，默认为-1，读取所有数据

#使用range 函数创建列表对象
list = range(5)
it = iter(list)

# 使用迭代器创建 ndarray
x = np.fromiter(it, dtype = float)
print(x)


[0. 1. 2. 3. 4.]


In [65]:
# 5、numpy.arange 从数值范围创建数组
# numpy.arange(start, stop, step, dtype)
# start 起始值：默认为0 stop:终止值（不包括）step: 步长，默认为1
# dtype 返回ndarray的数据类型， 如果没有提供，则会使用输入数据的类型
x = np.arange(5)
print(x)


[0 1 2 3 4]


In [66]:
# 设置返回类型 dtype
x = np.arange(5, dtype = float)
print(x)

[0. 1. 2. 3. 4.]


In [68]:
#设置起始值，终止值及步长
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [71]:
#numpy.linspace 用于创建一个一维数组 ，数组 是一个等差数列构成的，格式如下：
# np.linspace(start, stop, num = 50, endpoint = True, restep = Flase, dtype = None)

#endpoint 为True时，数列 中包含stop的值，反之不包含，默认是True
#retstep 为True时，生成的数组中会显示 间距，反之不显示 

a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [74]:
a = np.linspace(1,10,10,retstep = True)
print(a)

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), 1.0)


In [76]:
a = np.linspace(1,1,10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [77]:
a = np.linspace(1,2,5)
print(a)

[1.   1.25 1.5  1.75 2.  ]


In [78]:
#拓展例子

b = np.linspace(1,10,10).reshape([10, 1])
print(b)

[[ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]
 [ 9.]
 [10.]]


In [79]:
#numpy.logspace 函数用于创建一个等比数列 格式如下 ：
#numpy.logspace(start, stop, num = 50, endpoint = True, bas = 10.0, dtype =None)
#base 参数意思是取对数的时候 log 的下标。
#start 起始值为：base**start,base的start次方，也就是数学中对数的真值
#stop  终止值为：base**stop.如果 endpoint为Trye，该值包含于数列 中
#num 要生成的等步长的样本数量，默认为50
#endpoint 默认为True
#默认底数是10
a = np.logspace(1.0, 2.0,num = 10 )
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [81]:
#将对数的底数设置为2
a = np.logspace(0,9,10,base = 2)
print(a)

[  1.   2.   4.   8.  16.  32.  64. 128. 256. 512.]
