In [30]:
import numpy as np
x = np.zeros((5,8),dtype = 'i4')
y = np.linspace(1, 5, 8,dtype = 'i4')
z = np.arange(1,16,2)
a = x + y
b = x + z
c = a +b
print("x的值：")
print(x)
print("\n")
print("x+y的值：") #触发广播
print(a)
print("\n")
print("z的值：")
print(z)
print("\n")
print("x+z的值：") #触发广播
print("\n")
print(b)
print("\n")
print("a+b的值：")
print(c)
#print(a*b)

x的值：
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


x+y的值：
[[1 1 2 2 3 3 4 5]
 [1 1 2 2 3 3 4 5]
 [1 1 2 2 3 3 4 5]
 [1 1 2 2 3 3 4 5]
 [1 1 2 2 3 3 4 5]]


z的值：
[ 1  3  5  7  9 11 13 15]


x+z的值：


[[ 1  3  5  7  9 11 13 15]
 [ 1  3  5  7  9 11 13 15]
 [ 1  3  5  7  9 11 13 15]
 [ 1  3  5  7  9 11 13 15]
 [ 1  3  5  7  9 11 13 15]]


a+b的值：
[[ 2  4  7  9 12 14 17 20]
 [ 2  4  7  9 12 14 17 20]
 [ 2  4  7  9 12 14 17 20]
 [ 2  4  7  9 12 14 17 20]
 [ 2  4  7  9 12 14 17 20]]


In [31]:
# 8 、numpy 迭代数组
# numpy迭代器对象 numpy.nditer
import numpy as np

a = np.arange(6).reshape(2,3)
print("原始数据是：")
print(a)
print("\n")

print("迭代输出元素：")
for x in np.nditer(a):
    print(x, end=",")
print('\n')


原始数据是：
[[0 1 2]
 [3 4 5]]


迭代输出元素：
0,1,2,3,4,5,



In [33]:
import numpy as np
 
a = np.arange(6).reshape(2,3)
for x in np.nditer(a.T):
    print (x, end=", " )
print ('\n')
 
for x in np.nditer(a.T.copy(order='C')):  #通过迭代上述数组的转置来看到这一点，
                                         #并与以 C 顺序访问数组转置的 copy 方式做对比
    print (x, end=", " )
print ('\n')

0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



In [35]:
# 控制遍历顺序 #for x in np.nditer(a, order='F'):Fortran order，即是列序优先；
# for x in np.nditer(a.T, order='C'):C order，即是行序优先；  
import numpy as np

a = np.arange(0, 60, 5).reshape(3,4)
print('原始数组是：')
print(a)
print('\n')
print('原始数组的转置是：')
b = a.T
print(b)
print('\n')
print('以C风格顺序排序：')
c = b.copy(order = 'C')
print(c)
for x in np.nditer(c):
    print(x, end = ',')
print('\n')
print('以F风格顺序排序：')
c = b.copy(order = 'F')
print(c)
for x in np.nditer(c):
    print(x, end = ',')

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以C风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0,20,40,5,25,45,10,30,50,15,35,55,

以F风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0,5,10,15,20,25,30,35,40,45,50,55,

In [37]:
# 修改数组中元素的值
# nditer对象有另一个可先参数op_flags，默认情况下，nditer交视待迭代遍历的数组 为只读对象(read-only)
# 为了在遍历数组的同时，实现对数组元素值进行修改，必须指定read-write 或者是write-only模式

import numpy as np
a =np.arange(0,60,5).reshape(3,4)
print('原始数组是：')
print(a)
print('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 2 * x
print('修改后的数组是:')
print(a)

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


修改后的数组是:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [38]:
# 广播迭代
# 如果两个数组是可广播的，nditer组合对象同时迭代它们
import numpy as np

a = np.arange(0,60,5).reshape(3,4)
print('第一个数组为：')
print(a)
print('\n')
print('第二个数组为：')
b = np.array([1, 2, 3, 4], dtype =int)
print(b)
print('\n')
print('修改后的数组为：')
for  x,y in np.nditer([a, b]):
    print("%d:%d" % (x,y),end = ',')


第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1,5:2,10:3,15:4,20:1,25:2,30:3,35:4,40:1,45:2,50:3,55:4,

In [39]:
# 9、numpy 数组操作
# numpy中含了以下用于处理数组的常用函数
# 1）修改数组形状 2）翻转数组 3）修改数组维度
# 4） 连接数组 5）分割数组 6）数组元素的添加与删除



In [41]:
# 1）修改数组形状  
#  reshape 不改变数据的条件下修改形状
# 格式：numpy.reshape(arr, newshape, order = 'C')
# arr 要修改形状的数组
# newshape: 整数或者整数数组，新的形状应当兼容原有形状
# order:'C'--按行，‘F’--按列，‘A’-按顺序，‘k'--按元素在内存中的出现的顺序
#实例：
import numpy as np

a = np.arange(8)
print('原始数组是：')
print(a)
print('\n')

b = a.reshape(4,2)
print('修改后的数组是：')
print(b)


原始数组是：
[0 1 2 3 4 5 6 7]


修改后的数组是：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [43]:
# flat 数组元素迭代器
import numpy as np

a = np.arange(9).reshape(3,3)
print("原始数组：")
for row in a:
    print(row)
# 对数组中每个元素都进行处理，可以使用flat属性，该属性是一个数组元素迭代器：
print("迭代后的数组 ：")
for element in a.flat:
    print(element)

原始数组：
[0 1 2]
[3 4 5]
[6 7 8]
迭代后的数组 ：
0
1
2
3
4
5
6
7
8


In [45]:
# flatten 返回一份数组拷贝，对拷贝的修改不会影响原始数组
# numpy.ndarray.flatten 返回一份数组拷贝，对拷贝所做的修改不会影响原始数组，格式如下：
# numpy.flatten(order='c')

import numpy as np
a = np.arange(8).reshape(2,4)

print('原数组：')
print(a)
print('\n')
print ('展开的数组：')
print(a.flatten())
print('\n')

print('以F 风格顺序展开的数组：')
print(a.flatten(order = 'F'))



原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


In [48]:
# ravel 返回展开数组
# numpy.revel() 展开数组元素，顺序通常是“C风格”，返回的是数组的视图（view,有点类似
# C/C++引用reference的意味），修改会影响原始数组 该函数接收两个参数：
# numpy.revel(a,order = 'c')
# order: 'C'--按行，'F'--按列，‘A’--原顺序，‘K’--元素在内存中的出现顺序
#实例：
import numpy as np

a = np.arange(8).reshape(2,4)
print('原数组：')
print(a)
print('\n')

print('调用 revel 函数之后：')
print(a.ravel())
print('\n')

print('以F 风格顺序调用ravel 函数之后：')
print(a.ravel(order = "F"))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 revel 函数之后：
[0 1 2 3 4 5 6 7]


以F 风格顺序调用ravel 函数之后：
[0 4 1 5 2 6 3 7]


In [49]:
#翻转数组：
#numpy.transpose 函数用于对换数组的维度，格式如下 ：
# numpy.transpose(arr,axes)
# arr 要操作的数组
# axes 整数列表，对应维度，通常所有维度都会对换

In [50]:
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (np.transpose(a))

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [51]:
#numpy.ndarray.T 类似 numpy.transpose：
import numpy as np
 
a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')
 
print ('对换数组：')
print (a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [52]:
#numpy.rollaxis
# numpy.rollaxis 函数向后滚动特定的轴到一个特定位置，格式如下：
#numpy.rollaxis(arr, axis, start)
#参数说明：

#arr：数组
#axis：要向后滚动的轴，其它轴的相对位置不会改变
#start：默认为零，表示完整的滚动。会滚动到特定位置。

In [53]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 将轴 2 滚动到轴 0（宽度到深度）
 
print ('调用 rollaxis 函数：')
print (np.rollaxis(a,2))
# 将轴 0 滚动到轴 1：（宽度到高度）
print ('\n')
 
print ('调用 rollaxis 函数：')
print (np.rollaxis(a,2,1))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用 rollaxis 函数：
[[[0 2]
  [4 6]]

 [[1 3]
  [5 7]]]


调用 rollaxis 函数：
[[[0 2]
  [1 3]]

 [[4 6]
  [5 7]]]


In [57]:
#numpy.swapaxes
#numpy.swapaxes 函数用于交换数组的两个轴，格式如下：
# numpy.swapaxes(arr, axis1, axis2)
# arr：输入的数组
# axis1：对应第一个轴的整数
# axis2：对应第二个轴的整数
print(a.T)

[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [56]:
import numpy as np
 
# 创建了三维的 ndarray
a = np.arange(8).reshape(2,2,2)
 
print ('原数组：')
print (a)
print ('\n')
# 现在交换轴 0（深度方向）到轴 2（宽度方向）
 
print ('调用 swapaxes 函数后的数组：')
print (np.swapaxes(a, 2, 0))

原数组：
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


调用 swapaxes 函数后的数组：
[[[0 4]
  [2 6]]

 [[1 5]
  [3 7]]]


In [58]:
# 修改数组维度
# numpy.broadcast
# numpy.broadcast 用于模仿广播的对象，它返回一个对象，
# 该对象封装了将一个数组广播到另一个数组的结果。

# 该函数使用两个数组作为输入参数，如下实例：

In [62]:
import numpy as np

x = np.array([[1], [2,], [3]])
y = np.array([4, 5, 6])

# 对y 广播 x
b = np.broadcast(x, y)
# 它拥有 iterator 属性，基于自身组件的迭代器元组
print('对y 广播x:')
r, c = b.iters
# Python3.x 为 next(context) ，Python2.x 为 context.next()
print (next(r), next(c))
print (next(r), next(c))
print ('\n')
# shape 属性返回广播对象的形状
 
print ('广播对象的形状：')
print (b.shape)
print ('\n')
# 手动使用 broadcast 将 x 与 y 相加
b = np.broadcast(x,y)
c = np.empty(b.shape)
 
print ('手动使用 broadcast 将 x 与 y 相加：')
print (c.shape)
print ('\n')
c.flat = [u + v for (u,v) in b]
 
print ('调用 flat 函数：')
print (c)
print ('\n')
# 获得了和 NumPy 内建的广播支持相同的结果
 
print ('x 与 y 的和：')
print (x + y)

对y 广播x:
1 4
1 5


广播对象的形状：
(3, 3)


手动使用 broadcast 将 x 与 y 相加：
(3, 3)


调用 flat 函数：
[[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


x 与 y 的和：
[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
# numpy.broadcast_to
# numpy.broadcast_to 函数将数组广播到新形状。它在原始数组上返回只读视图。 它通常不连续。
# 如果新形状不符合 NumPy 的广播规则，该函数可能会抛出ValueError。
# numpy.broadcast_to(array, shape, subok)

In [63]:
import numpy as np
 
a = np.arange(4).reshape(1,4)
 
print ('原数组：')
print (a)
print ('\n')
 
print ('调用 broadcast_to 函数之后：')
print (np.broadcast_to(a,(4,4)))


原数组：
[[0 1 2 3]]


调用 broadcast_to 函数之后：
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [64]:
# numpy.expand_dims
# numpy.expand_dims 函数通过在指定位置插入新的轴来扩展数组形状，函数格式如下:
# numpy.expand_dims(arr, axis)
# arr：输入数组
# axis：新轴插入的位置

In [74]:
import numpy as np

#x = np.array(([1,2], [3, 4]))
x = np.arange(1,5).reshape(2,2) # 与上面那创建数组的方法效果一样

print('数组x:')
print(x)
print('\n')
y = np.expand_dims(x, axis = 0)

print('数组y:')
print(y)
print('\n')

print ('数组 x 和 y 的形状：')
print (x.shape, y.shape)
print ('\n')
# 在位置 1 插入轴
y = np.expand_dims(x, axis = 1)

print ('在位置 1 插入轴之后的数组 y：')
print (y)
print ('\n')

print ('x.ndim 和 y.ndim：')
print (x.ndim,y.ndim)
print ('\n')
 
print ('x.shape 和 y.shape：')
print (x.shape, y.shape)

数组x:
[[1 2]
 [3 4]]


数组y:
[[[1 2]
  [3 4]]]


数组 x 和 y 的形状：
(2, 2) (1, 2, 2)


在位置 1 插入轴之后的数组 y：
[[[1 2]]

 [[3 4]]]


x.ndim 和 y.ndim：
2 3


x.shape 和 y.shape：
(2, 2) (2, 1, 2)
