In [4]:
#6、numpy 切片和索引
import numpy as np
a = np.arange(10)
s = slice(2,7,2) #从索引2开始到索引7停止，间隔为2
print(a[s])

[2 4 6]


In [5]:
b = a[2:7:2]  #从索引2开始到索引7停止，间隔为2
print(b)

[2 4 6]


In [6]:
c = a[2:]
print(c)

[2 3 4 5 6 7 8 9]


In [7]:
# 切片还可以包括省略号...，来使选择元组的长度与数组 的维度相同，如果在行位置使用省略号，
# 它将返回包含行中元素的ndarray
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a[...,1])   # 第2列元素
print(a[1,...])   # 第2行元素
print(a[...,1:])   # 第2列及剩下的所有元素


[2 4 5]
[3 4 5]
[[2 3]
 [4 5]
 [5 6]]


In [9]:
# 7、numpy高级索引
# 1）、整数数级索引
#以下实例获取数组中(0,0)，(1,1)和(2,0)位置处的元素。
import numpy as np

x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

[1 4 5]


In [11]:
# 以下实例获取了 4X3 数组中的四个角的元素。 
# 行索引是 [0,0] 和 [3,3]，而列索引是 [0,2] 和 [0,2]。
import numpy as np

x = np.array([[  0,  1,  2],[  3,  4,  5],[  6,  7,  8],[  9,  10,  11]]) 
print("我们的数组是：")
print(x)
print ('\n')
rows = np.array([[0,0],[3,3]])
cols = np.array([[0,2],[0,2]])
y = x[rows,cols]  
print  ('这个数组的四个角元素是：')
print (y)

我们的数组是：
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


这个数组的四个角元素是：
[[ 0  2]
 [ 9 11]]


In [15]:
print(x[0,0])
print(x[0,2])
print(x[3,0])
print(x[3,2])

0
2
9
11


In [16]:
#2、布尔索引 我们可以通过一个布尔数组 来索引目标数组 
#布尔索引通过布尔运算来猎取符合指定每件的元素的数组
import numpy as np

x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print ('我们的数组是：')
print (x)
print ('\n')
# 现在我们会打印出大于 5 的元素  
print  ('大于 5 的元素是：')
print (x[x >  5])

我们的数组是：
[[ 1  2  3]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


大于 5 的元素是：
[ 6  7  8  9 10 11]


In [24]:
# 3、花式索引指的是利用整数数组进行索引
#花式索引根据索引数组的值作为目标数组的某个轴的下标来取值。
#对于使用一维整型数组作为索引，如果目标是一维数组，那么索引的结果就是对应位置的元素；
#如果目标是二维数组，那么就是对应下标的行。

#花式索引跟切片不一样，它总是将数据复制到新数组中。


#（1）传入顺序索引数组
x = np.arange(32).reshape((8, 4))
print ('我们的数组是：')
print(x)
print ('\nx[[4, 2, 1, 7]]是：\n')
print(x[[4, 2, 1, 7]])

我们的数组是：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

x[[4, 2, 1, 7]]是：

[[16 17 18 19]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [28 29 30 31]]


In [26]:
# （2）传入顺序索引数组
x = np.arange(32).reshape((8, 4))
print ('我们的数组是：')
print(x)
print ('\nx[[-4,-2, -1, -7]]是：\n')
print(x[[-4, -2, -1, -7]])


我们的数组是：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]

x[[-4,-2, -1, -7]]是：

[[16 17 18 19]
 [24 25 26 27]
 [28 29 30 31]
 [ 4  5  6  7]]


In [27]:
#（3）传入多个索引数组（要使用np.ix_）
x=np.arange(32).reshape((8,4))
print (x[np.ix_([1,5,7,2],[0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [29]:
#numpy 广播
#广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式，
#对数组的算术运算通常在相应的元素上进行。

#如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，
#那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。

import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a + b
print(c)



[11 22 33 44]


In [32]:
# 当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：
a = np.array([[ 0, 0, 0],
           [10,10,10],
           [20,20,20],
           [30,30,30]])
b = np.array([1,2,3])
print(a + b)

# 4x3 的二维数组与长为 3 的一维数组相加，等效于把数组 b 在二维上重复 4 次再运算：

[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [35]:

#广播的规则:

#让所有输入数组都向其中形状最长的数组看齐，形状中不足的部分都通过在前面加 1 补齐。
#输出数组的形状是输入数组形状的各个维度上的最大值。
#如果输入数组的某个维度和输出数组的对应维度的长度相同或者其长度为 1 时，这个数组能够用来计算，否则出错。
#当输入数组的某个维度的长度为 1 时，沿着此维度运算时都用此维度上的第一组值。
#简单理解：对两个数组，分别比较他们的每一个维度（若其中一个数组没有当前维度则忽略），满足：

#数组拥有相同形状。
#当前维度的值相等。
#当前维度的值有一个是 1。
#若条件不满足，抛出 "ValueError: frames are not aligned" 异常。

